payum:
    security:
        token_storage:
            Sylius\Bundle\CoreBundle\Model\PaymentToken:
                filesystem:
                    storage_dir: %kernel.root_dir%/Resources/payments
                    id_property: hash

    contexts:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox: true
                actions:
                    - sylius.payum.action.capture_order_with_paypal
                    - sylius.payum.action.order_status

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\CoreBundle\Model\PaypalPaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id

        stripe:
            omnipay:
                type: Stripe
                options:
                    apiKey:  %stripe.secret_key%
                    testMode: true
                actions:
                    - sylius.payum.action.capture_order_with_stripe
                    - sylius.payum.action.order_status

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                        payment_extension: true
                Sylius\Bundle\CoreBundle\Model\StripePaymentDetails:
                    filesystem:
                        storage_dir: %kernel.root_dir%/Resources/payments
                        id_property: id